name: base
channels:
  - defaults
dependencies:
  - archspec=0.2.1=pyhd3eb1b0_0
  - boltons=23.0.0=py311hca03da5_0
  - brotli-python=1.0.9=py311h313beb8_7
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2023.12.12=hca03da5_0
  - certifi=2023.11.17=py311hca03da5_0
  - cffi=1.16.0=py311h80987f9_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=23.11.0=py311hca03da5_0
  - conda-content-trust=0.2.0=py311hca03da5_0
  - conda-libmamba-solver=23.12.0=pyhd3eb1b0_1
  - conda-package-handling=2.2.0=py311hca03da5_0
  - conda-package-streaming=0.9.0=py311hca03da5_0
  - cryptography=41.0.7=py311hd4332d6_0
  - distro=1.8.0=py311hca03da5_0
  - fmt=9.1.0=h48ca7d4_0
  - icu=73.1=h313beb8_0
  - idna=3.4=py311hca03da5_0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=hf3e1bf2_1
  - libarchive=3.6.2=h62fee54_2
  - libcurl=8.4.0=h3e2b118_1
  - libcxx=14.0.6=h848a8c0_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_0
  - libiconv=1.16=h1a28f6b_2
  - libmamba=1.5.3=h15e39b3_0
  - libmambapy=1.5.3=py311h1c5506f_0
  - libnghttp2=1.57.0=h62f6fdd_0
  - libsolv=0.7.24=h514c7bf_0
  - libssh2=1.10.0=h02f6b3c_2
  - libxml2=2.10.4=h0dcf63f_1
  - lz4-c=1.9.4=h313beb8_0
  - menuinst=2.0.1=py311hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.12=h1a28f6b_0
  - packaging=23.1=py311hca03da5_0
  - pcre2=10.42=hb066dcc_0
  - pip=23.3.1=py311hca03da5_0
  - platformdirs=3.10.0=py311hca03da5_0
  - pluggy=1.0.0=py311hca03da5_1
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.6=py311h80987f9_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.5=hb885b13_0
  - python.app=3=py311h80987f9_0
  - readline=8.2=h1a28f6b_0
  - reproc=14.2.4=hc377ac9_1
  - reproc-cpp=14.2.4=hc377ac9_1
  - requests=2.31.0=py311hca03da5_0
  - ruamel.yaml=0.17.21=py311h80987f9_0
  - setuptools=68.2.2=py311hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - tk=8.6.12=hb8d0fd4_0
  - tqdm=4.65.0=py311hb6e6a13_0
  - truststore=0.8.0=py311hca03da5_0
  - urllib3=1.26.18=py311hca03da5_0
  - wheel=0.41.2=py311hca03da5_0
  - xz=5.4.5=h80987f9_0
  - yaml-cpp=0.8.0=h313beb8_0
  - zlib=1.2.13=h5a0b063_0
  - zstandard=0.19.0=py311h80987f9_0
  - zstd=1.5.5=hd90d995_0
  - pip:
      - absl-py==2.1.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - cachetools==5.3.2
      - chex==0.1.7
      - click==8.1.7
      - cloudpickle==3.0.0
      - contextlib2==21.6.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - dm-env==1.6
      - dm-meltingpot==2.2.0
      - dm-tree==0.1.8
      - dmlab2d==1.0.0
      - docker-pycreds==0.4.0
      - farama-notifications==0.0.4
      - filelock==3.13.1
      - flatbuffers==23.5.26
      - fonttools==4.47.2
      - fsspec==2023.12.2
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.41
      - google-auth==2.26.2
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - grpcio==1.60.0
      - gymnasium==0.29.1
      - h5py==3.10.0
      - immutabledict==4.1.0
      - jax==0.4.23
      - jaxlib==0.4.23
      - jinja2==3.1.3
      - keras==2.15.0
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - markdown==3.5.2
      - markupsafe==2.1.4
      - matplotlib==3.8.2
      - ml-collections==0.1.1
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.3
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - pandas==2.2.0
      - pettingzoo==1.24.3
      - pillow==10.2.0
      - protobuf==4.23.4
      - psutil==5.9.8
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pygame==2.5.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - reactivex==4.0.4
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scipy==1.12.0
      - sentry-sdk==1.39.2
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - stable-baselines3==2.2.1
      - supersuit==3.9.2
      - sympy==1.12
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-macos==2.15.0
      - termcolor==2.4.0
      - tinyscaler==1.2.7
      - toolz==0.12.0
      - torch==2.1.2
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - wandb==0.16.2
      - werkzeug==3.0.1
      - wrapt==1.14.1
prefix: /Users/Henry_1/miniconda3
